name: ethiosolar_app
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  badges: ^3.1.2
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  device_info_plus: ^10.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.2.4
  flutter_markdown: ^0.7.4+1
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.2
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  fvm: ^3.2.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_places_flutter: ^2.0.9
  http: ^1.1.2
  iconic: ^0.1.0
  iconsax: ^0.0.8
  image_picker: ^1.0.5
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  logger: ^2.4.0
  media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  motion_tab_bar: ^2.0.4
  photo_view: ^0.15.0

  pinput: ^5.0.0
  shared_preferences: ^2.2.2
  sizer: ^3.0.4

  syncfusion_flutter_pdfviewer: ^27.1.55
  timeago: ^3.6.0
  url_launcher: ^6.2.3
  webview_flutter: ^4.7.0
  with_helper: ^0.0.2
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#04a630"
  image: assets/images/logopower.png

  android_12:
    color: "#04a630"
    image: assets/images/splash.png
    icon_background_color: "#04a630"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logopower_old.png"
  image_path_android: "assets/images/logopower.png"
  min_sdk_android: 21
  remove_alpha_ios: true

build_runner: ^2.4.6
flutter_lints: ^3.0.1
flutter_test:
  sdk: flutter
freezed: ^2.4.3
json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/markdown/

  fonts:
    - family: Nyala
      fonts:
        - asset: assets/fonts/nyala.ttf
